# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: debug-statements
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: mixed-line-ending
      - id: requirements-txt-fixer

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          [flake8-bugbear, flake8-docstrings, flake8-keyword-arguments]
        args: [--config=pyproject.toml]
        exclude: |
          (?x)(
              ^docs/|
          )

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: ["--disallow-untyped-defs", "--ignore-missing-imports"]
        exclude: |
          (?x)(
              ^docs/|
          )

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]

  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: poetry run pytest -v --cov rov1
        files: "test_*"
        verbose: true
        language: system
        types: [python]
        stages: [push, manual]
