os: linux
arch:
  - arm64

language: python
python:
  - 3.8

cache:
pip: true
directories:
  - "$HOME/.cache/pre-commit"

before_install:
  - pip install poetry
  - pip install pre-commit
install:
  - poetry install
script:
  - pre-commit run --all-files
